### ISSUE TITLE
foodcritic runs once, then never again

### ISSUE THREAD

**Issue by ndobson** [AtomLinter/linter-foodcritic#11]
It seems like foodcritic runs on the recipe file I have open and works, but then if I switch to another recipe file that I know has a foodcritic issue and run Linter:lint it doesn't run again. Restarting atom shows the error on the second file but then shows no errors on the first.

Atom version 1.2.4

**Comment by Arcanemagus** [comment]
After linting the first file is there a `foodcritic` process hanging around?

**Comment by ndobson** [comment]
No, in fact if I do `watch -n1 "ps -ef | grep foodcritic"` I can see the foodcritic process launch then exit
